### ISSUE TITLE
Not displaying view correctly

### ISSUE THREAD

**Issue by MaikoHermans** [daihase/LSDialogViewController#1]
I'm trying to use the framework however I'm facing a couple of problems with it.

1. I added the `clipsToBounds` and `layer.cornerRadius` to the `Key Path` of my view. However this doesn't seem to do anything it will just draw a rectangle with no margin in between the view and the superview.

2. When trying to test the example project this doesn't work since there are a couple of errors. Do you have any idea what might be causing this?

note:
looking at the frameworks inside the `pods project` the quartz core framework (and the others) are all red

**Comment by daihase** [comment]
@MaikoHermans 
Sorry for the late reply.

About problem 1,
Does this mean that even if you do clipsToBounds and layer.cornerRadius, there is an invisible rectangular area? In the case of
I did not understand the intention of the question, sorry.

About problem 2,
It is a sample project, but when I clone in Xcode 8.3.2 I succeeded in building. Do you get errors even in the latest environment?
