### ISSUE TITLE
Can not Select item outside of dialog

### ISSUE THREAD

**Issue by ctthanh** [daihase/LSDialogViewController#2]
![9-21-2017 10-51-40 am](https://user-images.githubusercontent.com/30405006/30678255-2d067af0-9ebb-11e7-9b2e-d37fc7f67c86.png)

How do i fix this? thankz

**Comment by daihase** [comment]
@ctthanh 
Sorry for late reply.
Basically, in the case of View created based on xib, it is necessary to put content in the background view.  There is an example to display with xib, please refer to there.
