### ISSUE TITLE
how to disable dismiss on background tap?

### ISSUE THREAD

**Issue by ismaiI1** [daihase/LSDialogViewController#3]
how to disable dismiss on background tap?

**Comment by daihase** [comment]
@invisible66 

LSDialogViewController allows fine adjustment by setting arguments for calling `presentDialogViewController()`

An example is shown below.
Please write `dismissButtonEnabled: false` as argument.
Then the view will not be dismissed even if you tap the background.

Example
-----
```
let dialogViewController: CustomViewController = CustomViewController(nibName:"CustomView", bundle: nil)

self.presentDialogViewController(dialogViewController, dismissButtonEnabled: false)
```

**Comment by ismaiI1** [comment]
Thanks..
