### ISSUE TITLE
Unexpectedly found nil while unwrapping optional value

### ISSUE THREAD

**Issue by febinfathah** [daihase/LSDialogViewController#4]
I am getting an error while dismissing the dialogue view programmatically.
<img width="890" alt="screen shot 2018-05-02 at 3 19 06 pm" src="https://user-images.githubusercontent.com/9946233/39517171-b46ebca8-4e1c-11e8-9648-bcfb08ac07f7.png">

**Comment by daihase** [comment]
@febinfathah 
Sorry for the late reply.
I also tried creating VC with code and calling it as a dialog. When dismissed, it was possible to close without error.


`SecondViewController`
```
import UIKit

class SecondViewController: UIViewController {
    required init?(coder aDecoder: NSCoder) { fatalError("init(coder:) has not been implemented") }
    
    init() {
        super.init(nibName: nil, bundle: nil)
        self.view.frame = CGRect(x: 40, y: 40, width: UIScreen.main.bounds.size.width - 80, height: UIScreen.main.bounds.size.height - 80)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .red
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
}

```

`ViewController`
```
func show() {
  // generated by code
  let secondVC = SecondViewController()
  // set LSDialogViewController's method
  self.presentDialogViewController(secondVC)
}
```

I actually checked the breakpoint at the part of the image you attached.
<img width="973" alt="uiviewcontroller_lsdialogviewcontroller_swift" src="https://user-images.githubusercontent.com/19318060/39968355-766c7c2c-5706-11e8-906e-c3e67038e8f3.png">

If the target sourceView (SecondViewController.view in the case of example) is not nil, it will not cause an error as above.

**Comment by febinfathah** [comment]
@daihase 
It was a wrong usage from my side. I was setting the dialogue view to nil before dismissing the view.

Thanks for your kind reply and time.

**Comment by asn111** [comment]
I am facing the same issue @febinfathah how did you resolved it
