### ISSUE TITLE
Get event into parent view controller on dialog disappear

### ISSUE THREAD

**Issue by kartikpatel211** [daihase/LSDialogViewController#6]
I want to get an event into parent view controller when dialog disappears while tap outside the dialog. I am not able to find any mechanism in your code to achieve this.

**Comment by daihase** [comment]
@kartikpatel211 
Sorry for the late reply.
Currently, there is no mechanism for tapping the outside the dialog and informing the parent of it eventually.

If you want to do it, you need to place an invisible button on the background and do it yourself with delegate mechanism.
